name: CD - Deploy ASP.NET App

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - staging
       
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of Docker image to deploy'
        required: true
      environment:
        description: 'Target environment'
        required: true

env:
  DOCKER_REPO: pptloc/aspnetapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          TAG="${{ github.event.inputs.image_tag || github.ref_name }}"
          ENV="${{ github.event.inputs.environment || 'production' }}"

          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+-(dev|staging|main)-(d|s|p)-[a-f0-9]{8}$ ]]; then
            echo "::error::❌ Invalid image tag format: $TAG"
            exit 1
          fi

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            TAG="${{ github.event.inputs.image_tag || github.ref_name }}"
            IMAGE="pptloc/aspnetapp:$TAG"

            echo "🚀 Deploying image: $IMAGE"

            docker pull $IMAGE
            docker stop aspnetapp || true
            docker rm aspnetapp || true

            docker run -d \
              --name aspnetapp \
              -p 80:8080 \
              $IMAGE