name: CI - Post Merge to Main

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: pptloc/aspnetapp

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet restore ./aspnet/aspnetapp/aspnetapp.sln
      - run: dotnet build ./aspnet/aspnetapp/aspnetapp.sln --no-restore
      - run: dotnet test ./aspnet/aspnetapp/aspnetapp.sln --no-build

  docker-build-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker tag
        id: set_tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          TAG="1.0.0-main-p-${SHORT_SHA}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Build Docker image
        run: docker build -t $DOCKER_REPO:$TAG .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push $DOCKER_REPO:$TAG
